### ISSUE TITLE
Dividir más la presentación 

### ISSUE THREAD

**Issue by MatiasLaguna** [pdep-utn-frd/presentacion-2021-tobiasgz#5]
Hola tobias, podrías agregar mas títulos o separaciones en la presentación para facilitar la lectura

**Comment by tobiasgz** [comment]
Hola, si claro no hay ningún problema, no lo había pensado ya que nunca hice una presentación pero es bueno tenerlo en cuenta.

**Comment by MatiasLaguna** [comment]
Perfecto tobias :)
